/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 */
const documents = {
    "\n  mutation GetLoginKey($username: String!) {\n    GetLoginKey(Username: $username)\n  }\n": types.GetLoginKeyDocument,
    "\n  mutation SignIn($username: String!, $key: String!) {\n    SignIn(Username: $username, Key: $key) {\n      AccessToken\n      User {\n        Id\n        Username\n        FirstName\n        LastName\n        Email\n        CreatedOn\n        Roles {\n          RoleName\n          Id\n        }\n      }\n    }\n  }\n": types.SignInDocument,
    "\n  query ValidateAuth {\n    ValidateAuth {\n      Id\n      Username\n      FirstName\n      LastName\n      Email\n      CreatedOn\n      Roles {\n        Id\n        RoleName\n      }\n    }\n  }\n": types.ValidateAuthDocument,
    "\n  query NetworkDevices($query: QueryArguments, $rsip: String) {\n    NetworkDevices(Query: $query, RSIP: $rsip) {\n      Id\n      CustomDesc\n      DeviceId\n      SubnetId\n      DeviceType\n      EnabledOn\n      Area {\n        Id\n        Name\n        ParentAreaId\n        Type\n        Details\n      }\n      NetworkBroadcaster {\n        Id\n        Name\n        _count {\n          NetworkDevices\n        }\n      }\n      Channels {\n        Id\n        CustomDesc\n        NodeDesc\n        NodeNo\n        NodeType\n        Status {\n          Id\n          StateName\n          StateType\n          StateValue\n        }\n      }\n      _count {\n        Channels\n      }\n      Enabled\n      DisabledBy\n      EnabledBy\n      DisabledOn\n    }\n  }\n": types.NetworkDevicesDocument,
    "\n  mutation SetDeviceDesc($deviceId: Int!, $description: String!) {\n    SetDeviceDesc(DeviceId: $deviceId, Description: $description) {\n      Id\n      Enabled\n      CustomDesc\n      DeviceId\n      SubnetId\n      DeviceType\n      _count {\n        Channels\n      }\n    }\n  }\n": types.SetDeviceDescDocument,
    "\n  mutation SetDeviceNodeDesc($nodeId: Int!, $description: String!) {\n    SetDeviceNodeDesc(NodeId: $nodeId, Description: $description) {\n      CustomDesc\n      Id\n      NodeDesc\n      NodeNo\n      NodeType\n      Status {\n        Id\n        StateName\n        StateType\n        StateValue\n      }\n    }\n  }\n": types.SetDeviceNodeDescDocument,
    "\n  mutation AddDeviceToRoom($deviceId: Int!, $roomId: Int) {\n    AddDeviceToRoom(DeviceId: $deviceId, RoomId: $roomId) {\n      Id\n      DeviceId\n      SubnetId\n      DeviceType\n      _count {\n        Channels\n      }\n      Enabled\n      CustomDesc\n      AreaId\n    }\n  }\n": types.AddDeviceToRoomDocument,
    "\n  mutation DelDevice($deviceId: Int!) {\n    DelDevice(DeviceId: $deviceId)\n  }\n": types.DelDeviceDocument,
    "\n  query Properties {\n    Properties {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      DeviceCount\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n": types.PropertiesDocument,
    "\n  query PropertyLevels($propertyId: Int!) {\n    PropertyLevels(PropertyId: $propertyId) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      DeviceCount\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n": types.PropertyLevelsDocument,
    "\n  query LevelUnits($levelId: Int!) {\n    LevelUnits(LevelId: $levelId) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      DeviceCount\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n": types.LevelUnitsDocument,
    "\n  query AreaByKeyword($filter: String!) {\n    AreaByKeyword(filter: $filter) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      DeviceCount\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n": types.AreaByKeywordDocument,
    "\n  mutation SaveProperty($property: PropertyAreaInput!) {\n    SaveProperty(Property: $property) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n": types.SavePropertyDocument,
    "\n  mutation SavePropertyLevel($level: LevelAreaInput!) {\n    SavePropertyLevel(Level: $level) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n": types.SavePropertyLevelDocument,
    "\n  mutation SavePropertyUnit($unit: UnitAreaInput!) {\n    SavePropertyUnit(Unit: $unit) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n": types.SavePropertyUnitDocument,
    "\n  mutation DeleteArea($areaIdList: [Int!]!) {\n    DeleteArea(AreaIdList: $areaIdList)\n  }\n": types.DeleteAreaDocument,
    "\n  query NetworkBroadcasters($query: QueryArguments) {\n    NetworkBroadcasters(Query: $query) {\n      Id\n      Name\n      AllowDevicesByDefault\n      Enabled\n      EnabledOn\n      EnabledBy\n      DisabledOn\n      DisabledBy\n      DetectedOn\n      LastMsgOn\n      NetworkDevices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        AreaId\n      }\n      _count {\n        NetworkDevices\n      }\n    }\n  }\n": types.NetworkBroadcastersDocument,
    "\n  query CurrentSourceFilters {\n    CurrentSourceFilters {\n      Id\n      RuleName\n      OrderNo\n      Ip\n      DeviceId\n      SubnetId\n      FilterAction\n      DetectedOn\n      UpdatedOn\n      UpdatedBy\n    }\n  }\n": types.CurrentSourceFiltersDocument,
    "\n  query PendingSourceFilters {\n    PendingSourceFilters {\n      Id\n      RuleName\n      OrderNo\n      Ip\n      DeviceId\n      SubnetId\n      DetectedOn\n    }\n  }\n": types.PendingSourceFiltersDocument,
    "\n  mutation UpdateFilter($filter: SystemFilterInput!) {\n    UpdateFilter(filter: $filter) {\n      Id\n      RuleName\n      OrderNo\n      Ip\n      DeviceId\n      SubnetId\n      FilterAction\n      DetectedOn\n      UpdatedOn\n      UpdatedBy\n    }\n  }\n": types.UpdateFilterDocument,
    "\n  mutation DeleteFilter($filterIds: [String!]!) {\n    DeleteFilter(filterIds: $filterIds)\n  }\n": types.DeleteFilterDocument,
    "\n  query AllUsers {\n    AllUsers {\n      Id\n      Username\n      FirstName\n      LastName\n      Roles {\n        RoleName\n      }\n      CreatedOn\n    }\n  }\n": types.AllUsersDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation GetLoginKey($username: String!) {\n    GetLoginKey(Username: $username)\n  }\n"): (typeof documents)["\n  mutation GetLoginKey($username: String!) {\n    GetLoginKey(Username: $username)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation SignIn($username: String!, $key: String!) {\n    SignIn(Username: $username, Key: $key) {\n      AccessToken\n      User {\n        Id\n        Username\n        FirstName\n        LastName\n        Email\n        CreatedOn\n        Roles {\n          RoleName\n          Id\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation SignIn($username: String!, $key: String!) {\n    SignIn(Username: $username, Key: $key) {\n      AccessToken\n      User {\n        Id\n        Username\n        FirstName\n        LastName\n        Email\n        CreatedOn\n        Roles {\n          RoleName\n          Id\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query ValidateAuth {\n    ValidateAuth {\n      Id\n      Username\n      FirstName\n      LastName\n      Email\n      CreatedOn\n      Roles {\n        Id\n        RoleName\n      }\n    }\n  }\n"): (typeof documents)["\n  query ValidateAuth {\n    ValidateAuth {\n      Id\n      Username\n      FirstName\n      LastName\n      Email\n      CreatedOn\n      Roles {\n        Id\n        RoleName\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query NetworkDevices($query: QueryArguments, $rsip: String) {\n    NetworkDevices(Query: $query, RSIP: $rsip) {\n      Id\n      CustomDesc\n      DeviceId\n      SubnetId\n      DeviceType\n      EnabledOn\n      Area {\n        Id\n        Name\n        ParentAreaId\n        Type\n        Details\n      }\n      NetworkBroadcaster {\n        Id\n        Name\n        _count {\n          NetworkDevices\n        }\n      }\n      Channels {\n        Id\n        CustomDesc\n        NodeDesc\n        NodeNo\n        NodeType\n        Status {\n          Id\n          StateName\n          StateType\n          StateValue\n        }\n      }\n      _count {\n        Channels\n      }\n      Enabled\n      DisabledBy\n      EnabledBy\n      DisabledOn\n    }\n  }\n"): (typeof documents)["\n  query NetworkDevices($query: QueryArguments, $rsip: String) {\n    NetworkDevices(Query: $query, RSIP: $rsip) {\n      Id\n      CustomDesc\n      DeviceId\n      SubnetId\n      DeviceType\n      EnabledOn\n      Area {\n        Id\n        Name\n        ParentAreaId\n        Type\n        Details\n      }\n      NetworkBroadcaster {\n        Id\n        Name\n        _count {\n          NetworkDevices\n        }\n      }\n      Channels {\n        Id\n        CustomDesc\n        NodeDesc\n        NodeNo\n        NodeType\n        Status {\n          Id\n          StateName\n          StateType\n          StateValue\n        }\n      }\n      _count {\n        Channels\n      }\n      Enabled\n      DisabledBy\n      EnabledBy\n      DisabledOn\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation SetDeviceDesc($deviceId: Int!, $description: String!) {\n    SetDeviceDesc(DeviceId: $deviceId, Description: $description) {\n      Id\n      Enabled\n      CustomDesc\n      DeviceId\n      SubnetId\n      DeviceType\n      _count {\n        Channels\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation SetDeviceDesc($deviceId: Int!, $description: String!) {\n    SetDeviceDesc(DeviceId: $deviceId, Description: $description) {\n      Id\n      Enabled\n      CustomDesc\n      DeviceId\n      SubnetId\n      DeviceType\n      _count {\n        Channels\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation SetDeviceNodeDesc($nodeId: Int!, $description: String!) {\n    SetDeviceNodeDesc(NodeId: $nodeId, Description: $description) {\n      CustomDesc\n      Id\n      NodeDesc\n      NodeNo\n      NodeType\n      Status {\n        Id\n        StateName\n        StateType\n        StateValue\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation SetDeviceNodeDesc($nodeId: Int!, $description: String!) {\n    SetDeviceNodeDesc(NodeId: $nodeId, Description: $description) {\n      CustomDesc\n      Id\n      NodeDesc\n      NodeNo\n      NodeType\n      Status {\n        Id\n        StateName\n        StateType\n        StateValue\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation AddDeviceToRoom($deviceId: Int!, $roomId: Int) {\n    AddDeviceToRoom(DeviceId: $deviceId, RoomId: $roomId) {\n      Id\n      DeviceId\n      SubnetId\n      DeviceType\n      _count {\n        Channels\n      }\n      Enabled\n      CustomDesc\n      AreaId\n    }\n  }\n"): (typeof documents)["\n  mutation AddDeviceToRoom($deviceId: Int!, $roomId: Int) {\n    AddDeviceToRoom(DeviceId: $deviceId, RoomId: $roomId) {\n      Id\n      DeviceId\n      SubnetId\n      DeviceType\n      _count {\n        Channels\n      }\n      Enabled\n      CustomDesc\n      AreaId\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DelDevice($deviceId: Int!) {\n    DelDevice(DeviceId: $deviceId)\n  }\n"): (typeof documents)["\n  mutation DelDevice($deviceId: Int!) {\n    DelDevice(DeviceId: $deviceId)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Properties {\n    Properties {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      DeviceCount\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n"): (typeof documents)["\n  query Properties {\n    Properties {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      DeviceCount\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query PropertyLevels($propertyId: Int!) {\n    PropertyLevels(PropertyId: $propertyId) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      DeviceCount\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n"): (typeof documents)["\n  query PropertyLevels($propertyId: Int!) {\n    PropertyLevels(PropertyId: $propertyId) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      DeviceCount\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query LevelUnits($levelId: Int!) {\n    LevelUnits(LevelId: $levelId) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      DeviceCount\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n"): (typeof documents)["\n  query LevelUnits($levelId: Int!) {\n    LevelUnits(LevelId: $levelId) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      DeviceCount\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query AreaByKeyword($filter: String!) {\n    AreaByKeyword(filter: $filter) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      DeviceCount\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n"): (typeof documents)["\n  query AreaByKeyword($filter: String!) {\n    AreaByKeyword(filter: $filter) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      DeviceCount\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation SaveProperty($property: PropertyAreaInput!) {\n    SaveProperty(Property: $property) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation SaveProperty($property: PropertyAreaInput!) {\n    SaveProperty(Property: $property) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation SavePropertyLevel($level: LevelAreaInput!) {\n    SavePropertyLevel(Level: $level) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation SavePropertyLevel($level: LevelAreaInput!) {\n    SavePropertyLevel(Level: $level) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation SavePropertyUnit($unit: UnitAreaInput!) {\n    SavePropertyUnit(Unit: $unit) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation SavePropertyUnit($unit: UnitAreaInput!) {\n    SavePropertyUnit(Unit: $unit) {\n      Id\n      Name\n      Type\n      Details\n      ParentAreaId\n      CreatedOn\n      CreatedBy\n      UpdatedOn\n      UpdatedBy\n      ParentArea {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      SubAreas {\n        Id\n        Name\n        Type\n        Details\n        ParentAreaId\n        CreatedOn\n        CreatedBy\n        UpdatedOn\n        UpdatedBy\n      }\n      Devices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        BroadcasterId\n        AreaId\n        Enabled\n        EnabledOn\n        EnabledBy\n        DisabledOn\n        DisabledBy\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteArea($areaIdList: [Int!]!) {\n    DeleteArea(AreaIdList: $areaIdList)\n  }\n"): (typeof documents)["\n  mutation DeleteArea($areaIdList: [Int!]!) {\n    DeleteArea(AreaIdList: $areaIdList)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query NetworkBroadcasters($query: QueryArguments) {\n    NetworkBroadcasters(Query: $query) {\n      Id\n      Name\n      AllowDevicesByDefault\n      Enabled\n      EnabledOn\n      EnabledBy\n      DisabledOn\n      DisabledBy\n      DetectedOn\n      LastMsgOn\n      NetworkDevices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        AreaId\n      }\n      _count {\n        NetworkDevices\n      }\n    }\n  }\n"): (typeof documents)["\n  query NetworkBroadcasters($query: QueryArguments) {\n    NetworkBroadcasters(Query: $query) {\n      Id\n      Name\n      AllowDevicesByDefault\n      Enabled\n      EnabledOn\n      EnabledBy\n      DisabledOn\n      DisabledBy\n      DetectedOn\n      LastMsgOn\n      NetworkDevices {\n        Id\n        CustomDesc\n        DeviceId\n        SubnetId\n        DeviceType\n        AreaId\n      }\n      _count {\n        NetworkDevices\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query CurrentSourceFilters {\n    CurrentSourceFilters {\n      Id\n      RuleName\n      OrderNo\n      Ip\n      DeviceId\n      SubnetId\n      FilterAction\n      DetectedOn\n      UpdatedOn\n      UpdatedBy\n    }\n  }\n"): (typeof documents)["\n  query CurrentSourceFilters {\n    CurrentSourceFilters {\n      Id\n      RuleName\n      OrderNo\n      Ip\n      DeviceId\n      SubnetId\n      FilterAction\n      DetectedOn\n      UpdatedOn\n      UpdatedBy\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query PendingSourceFilters {\n    PendingSourceFilters {\n      Id\n      RuleName\n      OrderNo\n      Ip\n      DeviceId\n      SubnetId\n      DetectedOn\n    }\n  }\n"): (typeof documents)["\n  query PendingSourceFilters {\n    PendingSourceFilters {\n      Id\n      RuleName\n      OrderNo\n      Ip\n      DeviceId\n      SubnetId\n      DetectedOn\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateFilter($filter: SystemFilterInput!) {\n    UpdateFilter(filter: $filter) {\n      Id\n      RuleName\n      OrderNo\n      Ip\n      DeviceId\n      SubnetId\n      FilterAction\n      DetectedOn\n      UpdatedOn\n      UpdatedBy\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateFilter($filter: SystemFilterInput!) {\n    UpdateFilter(filter: $filter) {\n      Id\n      RuleName\n      OrderNo\n      Ip\n      DeviceId\n      SubnetId\n      FilterAction\n      DetectedOn\n      UpdatedOn\n      UpdatedBy\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteFilter($filterIds: [String!]!) {\n    DeleteFilter(filterIds: $filterIds)\n  }\n"): (typeof documents)["\n  mutation DeleteFilter($filterIds: [String!]!) {\n    DeleteFilter(filterIds: $filterIds)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query AllUsers {\n    AllUsers {\n      Id\n      Username\n      FirstName\n      LastName\n      Roles {\n        RoleName\n      }\n      CreatedOn\n    }\n  }\n"): (typeof documents)["\n  query AllUsers {\n    AllUsers {\n      Id\n      Username\n      FirstName\n      LastName\n      Roles {\n        RoleName\n      }\n      CreatedOn\n    }\n  }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;